name: Build CSharpSourceObfuscator

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Обновили с v3 на v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4 # Обновили с v3 на v4
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      # Укажи путь к .sln файлу или главному .csproj
      run: dotnet restore CSharpSourceObfuscator.sln 

    - name: Build project
      # Здесь тоже добавь путь к файлу
      run: dotnet build CSharpSourceObfuscator.sln --configuration Release --no-restore

    - name: Publish RoslynObfuscator
      # Тут путь уже указан, это правильно
      run: dotnet publish RoslynObfuscator/RoslynObfuscator.csproj --configuration Release --no-build --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4 # САМОЕ ВАЖНОЕ: заменили на v4
      with:
        name: CSharpSourceObfuscator-exe
        path: ./publish/
